### ISSUE TITLE
Feature: Provide search over resources

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#11]
I'd like to start caching resource names in the Boltdb cache then use this [fuzzy search](https://github.com/sajari/fuzzy) to allow quick searching of resources. 

Currently in two minds as to whether the app should *crawl* all resources to build the cache or just only search over those that have been viewed in the past.

**Comment by stuartleeks** [comment]
I frequently use resource explorer for one-off config changes so would love an option for searching all resources 😀

**Comment by stuartleeks** [comment]
The [Resource List API](https://docs.microsoft.com/en-us/rest/api/resources/resources/list) is probably a good starting point. Could either query all or put in a filter (e.g. `$filter=substringof('searchTerm', 'name')` to do partial match on resource name)

**Comment by lawrencegripper** [comment]
A simple crawler is now build as part of #16 ... next step is to test this out a bit more and build the UI components to expose it in the tooling

**Comment by lawrencegripper** [comment]
I think, now that the `Azure Resource Graph` exists this is likely the best route to go down for search. The only issue would be replication lag but I think it's worth trying it out and seeing how well it fits.

**Comment by jjcollinge** [comment]
@lawrencegripper this should be closed right?

**Comment by lawrencegripper** [comment]
I was seeing this one as different from the filtering feature added. More like a global search bar similar to the portal but it's a big one to tackle and I'm not sure I'd use it that much.

**Comment by lawrencegripper** [comment]
I'm closing this one out as with the `/thisthing` based filtering I haven't felt that I needed this recently. Feel free to re-open/comment if you don't agree.
