### ISSUE TITLE
Copy to clipboard fails on WSL2

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#110]
Attempting to copy to clipboard fails running under WSL2 just gives:

```
Failed to copy to clipboard
```

**Comment by stuartleeks** [comment]
After adding the inner error text to the output message I now get

```
No clipboard utilities available. Please install xsel, xclip, or Termux:API add-on for termux-clipboard-get/set.
```

**Comment by stuartleeks** [comment]
Which led me to this issue: https://github.com/atotto/clipboard/issues/45

**Comment by lawrencegripper** [comment]
Ah nice, I've merged the PR so for now at least we'll see some more error details. Hopefully that PR gets merged soon and we can update to the newer version.

**Comment by stuartleeks** [comment]
Just sent a PR that handles this in azbrowse - we can remove if atotto gets this functionality merged in :-)
