### ISSUE TITLE
Create an introduction/feature guide with Gif showing various stuff

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#125]
Probably should include

- Filtering
- NavigateTo
- Demo Mode
- Actions
- ACI Logs
- Edit resources (maybe demo changing an ACI setting or WebApp setting)
- Delete 
- Metrics graphs

**Comment by stuartleeks** [comment]
For editing resources, should we show using GUI and Terminal editors?

**Comment by lawrencegripper** [comment]
Closing this one off now as @stuartleeks has excellent pr #183 which tackles it.
