### ISSUE TITLE
Azure CLI missing from .devcontainer

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#131]
Azure CLI is a requirement to run `azbrowse` and should therefore be included in the Dev Container definition. This will require adding Python too.

Currently running `azbrowse` inside the container results in:
```
AzBrowse is waiting for access to '~/.azbrowse.db', do you have another instance of azbrowse open?                     Loading db complete                                                                                                    2019/10/14 13:31:00 Current version is the latest                                                                      2019/10/14 13:31:02 Failed to load subscriptions: Failed to acquire auth token: exec: "az": executable file not found in $PATH
panic: Failed to load subscriptions: Failed to acquire auth token: exec: "az": executable file not found in $PATH
```

**Comment by lawrencegripper** [comment]
Ah good point. I've only very lightly played around with the dev container stuff... intending to use it more would love to have a PR to add it. Ideally we need to mount the hostpath with the `azure.json` creds too
