### ISSUE TITLE
Feature: Allow editing of resource Json and posting back to the API

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#14]
This would allow arbitrary edits to the configuration of the item by CTRL+E then CTRL+something to post the edit back to the resource.

**Comment by stuartleeks** [comment]
#49 allows a variant of this: For resources that allow `PUT` requests (based on swagger codegen), `Ctrl+U` to open the current JSON in VS Code. When the file is closed make the `PUT` request if the file has been updated.

**Comment by lawrencegripper** [comment]
I agree via swagger is the nicer way to do this as we know that the resource will accept the PATCH/PUT. 

Great work @stuartleeks !
