### ISSUE TITLE
Bug Demo mode EOF when parsing JSON

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#153]
When running azbrowse using the `--demo` flag, I get a an `unexpected EOF` error when parsing the JSON response. See below:

![azbrowse_bug](https://user-images.githubusercontent.com/7241190/68430738-88d4c380-01a8-11ea-9aa6-9e49c9e54749.png)

**Comment by lawrencegripper** [comment]
Thanks Joni now fixed :)
