### ISSUE TITLE
When updating an item the JSON is no longer formatted before getting to the editor

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#161]
When refactoring I removed some duplicate code which attempted to format each response from the API into an indented JSON. 

As we now have formatting in the `itemview` which behaves differently based on the content type I moved the code. 

The result is that you can view an item with nicely formatted JSON but when you move to updating it you see a single line of JSON as it was returned by the server. 

![editformatting](https://user-images.githubusercontent.com/1939288/68748345-2ccccd80-05f4-11ea-99d4-234a7f449985.gif)

**Comment by jjcollinge** [comment]
Will do this today when I get some time

**Comment by jjcollinge** [comment]
Looks like this also effects saving the json to clipboard

**Comment by jjcollinge** [comment]
#166 should have closed this
