### ISSUE TITLE
Panic on timeout

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#171]
I got a panic on timing out expanding an item - would be nicer to show an error and allow the user to retry

goroutine 1 [running]:                                                                                                                                     github.com/lawrencegripper/azbrowse/internal/pkg/views.(*ListWidget).ExpandCurrentSelection(0xc000c83700)                                                          /go/src/github.com/lawrencegripper/azbrowse/internal/pkg/views/list.go:219 +0x31b                                                                  github.com/lawrencegripper/azbrowse/internal/pkg/keybindings.ListExpandHandler.Fn.func1(0xc000ccf200, 0xc000cd02d0, 0xa, 0xc00067bd01)                             /go/src/github.com/lawrencegripper/azbrowse/internal/pkg/keybindings/listhandlers.go:320 +0x2a                                                     github.com/stuartleeks/gocui.(*Gui).execKeybindings(0xc000ccf200, 0xc000cd02d0, 0xc00067bd78, 0x700000000, 0x2, 0x3)                                               /go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:629 +0xc4                                                                                   github.com/stuartleeks/gocui.(*Gui).onKey(0xc000ccf200, 0xc00067bd78, 0x2, 0x0)                                                                                    /go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:593 +0x1b3                                                                                  github.com/stuartleeks/gocui.(*Gui).handleEvent(...)                                                                                                               /go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:413                                                                                         github.com/stuartleeks/gocui.(*Gui).MainLoop(0xc000ccf200, 0xc000618ea0, 0xc000ccf200)                                                                             /go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:373 +0x1e3                                                                                  main.run(0xc000618ea0)                                                                                                                                             /go/src/github.com/lawrencegripper/azbrowse/cmd/azbrowse/main.go:82 +0x223                                                                         main.handleRunCmd(0xc000618ea0, 0xc0001cd8f9, 0xc0001cd8fa, 0xc000268c50, 0x0)                                                                                     /go/src/github.com/lawrencegripper/azbrowse/cmd/azbrowse/cmd.go:28 +0x8b                                                                           main.handleCommandAndArgs()                                                                                                                                        /go/src/github.com/lawrencegripper/azbrowse/cmd/azbrowse/cmd.go:81 +0x2ad                                                                          main.main()                                                                                                                                                        /go/src/github.com/lawrencegripper/azbrowse/cmd/azbrowse/main.go:41 +0x20

**Comment by lawrencegripper** [comment]
Woop! `Shouldn't be possible` -> `Will occur during timeout`. Probably shouldn't panic here and instead just show an error message and let the user retry. 

```golang
	if err != nil {
		// Shouldn't be possible
		panic(err)
	}
```

**Comment by jjcollinge** [comment]
Yup seen this one too - status updates feels apt here
