### ISSUE TITLE
Add more masking to `--demo` mode

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#175]
I think it would be good if the `--demo` mode obscured more fields:

* anything that has a `Secret` suffix under `<web app>/config/authsettings/` 
* `<web app>/config/connectionstrings/` values
* `<web app>/config/appsettings/` values
* `<web app>/config/publishingcredentials/` values: `publishingPassword` and `scmUri`
* `<web app>/config/functions/token` value
* `<azure search>/listAdminKeys` values: `primaryKey` and `secondaryKey`
* `<azure search>/listQueryKeys` all `key` values

A good portion of these would be covered by masking values with suffices of `key`, `secret` or `password`

Thoughts?

**Comment by stuartleeks** [comment]
This could be a "good first issue" once scoped

**Comment by bengreenier** [comment]
I'm going to try and tackle this. First step (as i understand it) is to add the regex values that match each of the examples above to [demomode.go](https://github.com/lawrencegripper/azbrowse/blob/master/internal/pkg/views/demomode.go#L7) if they are not currently matching one of the existing values.

My plan of attack is to go get real values of the above types, generalize them to example values, add these examples to [demomode_test.go](https://github.com/lawrencegripper/azbrowse/blob/master/internal/pkg/views/demomode_test.go), and then add regex to address any failing tests. Hope that sounds reasonable (let me know if I'm way off).

**Comment by lawrencegripper** [comment]
Yup, sounds good to me. Thanks for taking a look at this it :)

**Comment by bengreenier** [comment]
https://github.com/clarkio/azure-mask/blob/master/src/content-script/mask-process.js#L3 might be relevant/interesting. Including a link mostly for my own thought process, or if others are interested.

**Comment by bengreenier** [comment]
We can close this now, I believe

**Comment by lawrencegripper** [comment]
Indeed - thanks!
