### ISSUE TITLE
Typo RecoveryWithCleainup() -> RecoveryWithCleanup()

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#181]
Typo in function signature `RecoveryWithCleainup()`

https://github.com/lawrencegripper/azbrowse/blob/eafc14061228f1b750b9820c4fdbc0f455eeba6b/internal/pkg/errorhandling/recovery.go#L24

**Comment by lawrencegripper** [comment]
Oh man, sorry good spot.
