### ISSUE TITLE
Loading DB should be deferred until needed

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#185]
Currently, commands such as `azbrowse --help` and `azbrowse --version` require loading the db. Not loading the db would allow either to be run while another instance of azbrowse is running, and would also make the output cleaner for these commands

E.g. 

```bash
$ azbrowse --help
Loading db ...
Loading db complete
Usage of run:
  -debug
    	run in debug mode
  -demo
    	run in demo mode to filter sensitive output
  -fuzzer int
    	run fuzzer (optionally specify the duration in minutes) (default -1)
  -navigate string
    	navigate to resource
```

**Comment by lawrencegripper** [comment]
Totally agree. Using `init` method is super nasty for this it means lots of tests also load the DB which isn't nice either. 

Might try and pick this up tonight.
