### ISSUE TITLE
Feature: Add operation status indicator

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#19]
Once an operation has been applied, it's be great if we could add an icon that indicated that the action is in progress and then completed. This extends the existing issue #15.

I was thinking we could add the following unicode/non-unicode icons next to the resource names:
Deleting = ☠️ / -
Updating = ⚙️ / ~
Creating (if supported) = 🧱 / +

The end of the operation could be indicated by disappearance of the status icon.

Something similar to below:
![icons](https://user-images.githubusercontent.com/7241190/50340372-a78b8680-0512-11e9-846d-0e3052fb32a8.png)

**Comment by lawrencegripper** [comment]
I'm going to re-open as I've only covered off half the use-case. Currently the indicators will appear for `ResourceGroups` but not for `Resources` in them. 

I was currently look at using https://azure.microsoft.com/en-us/features/resource-graph/ to do this as the current APIs don't make this performant (need a call per `resource`)
