### ISSUE TITLE
Bug: Devcontainer linter failure - composites

### ISSUE THREAD

**Issue by bengreenier** [lawrencegripper/azbrowse#193]
Hello, I'm not actually sure this is isolated to the devcontainer, but i suspect it is based on previous conversations we've had.

```
github.com/alecthomas/chroma.Rule composite literal uses unkeyed fieldscomposites
```

Which appears to be caused by [this structure](https://github.com/lawrencegripper/azbrowse/blob/master/internal/pkg/views/itemview.go#L184) - specifically all 19 similar structures in the same file near that area.

![image](https://user-images.githubusercontent.com/1167891/70316523-d417db80-1813-11ea-8aaa-1951b3b3e87c.png)

I suspect, the `//nolint:govet` comments are supposed to be preventing this type of warning, but aren't working for some reason (I'm not familiar enough with this stuff to diagnose the issue). That said - One [potential solution](https://stackoverflow.com/a/54548495) seems to be to simply disable that type of warning globally, but I'd assume that isn't desirable for the project.

**Comment by bengreenier** [comment]
To be clear, this __does not__ block the build. It's merely a small annoyance in the devcontainer dev experience.

**Comment by lawrencegripper** [comment]
Interesting, yeah I would have expected the `//nolint:govet` to do the trick. 

A possible middle ground between perfect and easy would be to update the `golint.toml` file to disable this specific warning type for the file/files in question:

https://github.com/lawrencegripper/azbrowse/blob/35560cb54a4bceefabe7abed17a3e4ef4cc800c2/.golangci.toml#L52-L64

Sound like an alright plan? (No going to say it's the best plan but don't have a better idea atm)

**Comment by bengreenier** [comment]
I can probably submit a quick fix for this tomorrow, stay tuned.

**Comment by bengreenier** [comment]
Currently "blocked" on #208

**Comment by bengreenier** [comment]
This is caused by [`vet`](https://golang.org/cmd/vet/)

```
✘-1 /workspaces/azbrowse [master ↓·2|✚ 1] 
12:08 # go vet ./internal/pkg/views/
# github.com/lawrencegripper/azbrowse/internal/pkg/views
internal/pkg/views/itemview.go:192:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:193:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:194:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:195:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:196:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:197:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:199:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:200:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:203:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:204:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:205:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:206:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:207:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:208:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:209:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:210:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:211:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:213:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
internal/pkg/views/itemview.go:216:5: github.com/alecthomas/chroma.Rule composite literal uses unkeyed fields
✘-2 /workspaces/azbrowse [master ↓·2|✚ 1] 
12:08 # go vet --composites=false ./internal/pkg/views/
```

As you can see, `--composites=false` fixes it. However, adding the following to the vscode settings still doesn't get the extension to ignore these:

```
"go.vetFlags": [
    "--composites=false"
]
```

which has me...very confused. Further, this error is __not__ present when the linter runs, at least via the shell.

**Comment by bengreenier** [comment]
See https://github.com/microsoft/vscode-go/issues/2960

**Comment by lawrencegripper** [comment]
hmmm I think `golangci-lint` runs `govet` under the covers and we have `golangci-lint` set as our linter so maybe the errors are coming via that. 

Set here: https://github.com/lawrencegripper/azbrowse/blob/d131377/.vscode/settings.json#L2

**Comment by bengreenier** [comment]
they are not.

**Comment by lawrencegripper** [comment]
arg :(

**Comment by bengreenier** [comment]
The extension is not supporting vetFlags when using the language server. When setting [the undocumented flag to disable the lang server](https://github.com/microsoft/vscode-go/blob/master/src/goLanguageServer.ts#L247), these problems disappear. Will continue investigation and see if it's possible to tune the language server config/implementation.

**Comment by bengreenier** [comment]
our language server appears to be `gopls`, which supports [very little configuration](https://github.com/golang/tools/blob/master/gopls/doc/settings.md). We can reproduce the failure using `gopls`:

```
gopls check internal/pkg/views/itemview.go
```

In theory a workaround might be possible (some missing config to gopls vet impl) - the [source for `check`](https://github.com/golang/tools/blob/master/internal/lsp/cmd/check.go) may have the answer..

**Comment by bengreenier** [comment]
Discussed out of band with @lawrencegripper a bit - I'm going to see if switching away from gopls (given this issue, and it's alpha status) is easy enough/the right fix here.

**Comment by bengreenier** [comment]
Some days you really need to just take a step back...

😔😔😔

My fix for this will be to just fix the error with a code change, since that makes for better code anyway.

**Comment by lawrencegripper** [comment]
Thank you! All good and merged now.
