### ISSUE TITLE
Rethink CI/CD and Integration test builds

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#195]
#194 is an example where the build failed to start on one occasion then failed on a build of that PR which should have passed.

All the odd simulating XServer with display etc should probably be revisited

**Comment by lawrencegripper** [comment]
Looking at this in more detail I'd like to move to re-using the `devcontainer` environment for the builds and simplify the web of scripts that have currently been built up. 

Given some of the issues we've seen I'd also like to attempt to move both integration and normal build onto CircleCI.

**Comment by lawrencegripper** [comment]
#200 is another example of the AzDO build failing

**Comment by lawrencegripper** [comment]
@bengreenier small world: just stumbled on this -> https://github.com/bengreenier/docker-xvfb/blob/master/README.md

Sounds much easier than my current xserver and dummy display hack

**Comment by bengreenier** [comment]
Oh cool! Can chat more about it later this week if you like - I've been hacking on similar stuff for a while, so if that's not a perfect fit might still be able to help brainstorm the right thing ™️

**Comment by lawrencegripper** [comment]
Moving away from Circle CI as I want to be able mount file from the workspace into the container during the build process and this isn't easily supported. 

> Mounting Folders
>
> **It is not possible to mount a volume from your job space into a container** in Remote Docker (and vice versa). You may use the docker cp command to transfer files between these two environments. 

https://circleci.com/docs/2.0/building-docker-images/
