### ISSUE TITLE
Title rendering bug in Windows Terminal

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#198]
Not sure if this repos in other terminals but if I build master and then navigate to a leaf resource. If I continually hit enter the title keeps getting re-appended like below.

![bug](https://user-images.githubusercontent.com/7241190/70547493-e1f99380-1b68-11ea-9c42-c663ae1f890a.PNG)

This did not repo on @bengreenier machine so need to investigate

**Comment by lawrencegripper** [comment]
I’ve seen instances of this on my machine, shamefully never investigated more.

**Comment by lawrencegripper** [comment]
This one appears to be fixed to me. I have a recollection of one of @stuartleeks changes fixing it up. Closing out we can re-open if it reoccurs.
