### ISSUE TITLE
Swagger-gen non-deterministic output (unsure)

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#202]
I'm seeing a weird behavior and tracking here to come back to it. 

It looks like I can end up with elements of the `swagger-generated` file appearing if different orders on subsequent runs:

![image](https://user-images.githubusercontent.com/1939288/70854630-26ad6380-1eb6-11ea-9830-5b539a8881c5.png)

My first reading of this is that the ordering has returned differently for some reason and so the file has been created, essentially the same, but with a different order of elements. 

Will continue to dig.

**Comment by lawrencegripper** [comment]
I've confirmed this on my box, oddly it only seems to be occurring on this endpoint definition. Between runs I see it make/unmake this change, not consistently but it does occur. Or I've missed something silly that I'm doing.

**Comment by lawrencegripper** [comment]
Another example of this occurring in the build - https://dev.azure.com/lawrencegripper/githubbuilds/_build/results?buildId=715&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=1085 

Going to have a look into this this morning.

**Comment by lawrencegripper** [comment]
I can reproduce the error around 1/10 times by running `make swagger-codegen`. I captured the output of the logs while the codegen is running and compared a run which produced a diff to one which didn't. These didn't show any difference other than the execution time. 

![image](https://user-images.githubusercontent.com/1939288/71655624-7c479400-2d2f-11ea-9d55-4f4c4547c315.png)

Have a feeling this is going to be a hard one to get to the bottom of.

**Comment by lawrencegripper** [comment]
Think I might have a theory about why this might happen, in the `MergeSwaggerPaths` code the endpoints are sorted excluding the `{variables}` section. 

In the above case the two endpoints `/{roleAssignmentId}` and `/{roleDefinitionId}` are therefor identical and the sort becomes non-deterministic at that point.

**Comment by stuartleeks** [comment]
ah, good spot!

I have a recollection that sorting on the `{variables}` part caused issues (maybe inconsistencies in the names in the swagger?). There has also been quite a bit of work in that area since the original implementation so I'll try to find some time to add sorting on all components of the url and see what the output shows

**Comment by lawrencegripper** [comment]
So talking this through there are two options. 

1. Move to using the full `endpoint.TemplatedPath` then sorting 
1. Adapt compare to start with `condensedPath` then if identical fallback to full path

**Comment by stuartleeks** [comment]
Would definitely be good/interesting to know whether there is still an issue if the full url is used for sorting :-)

**Comment by lawrencegripper** [comment]
So enabling the full sort you see some interesting results. Eyeballing them there is nothing which stands out to me as a problem. Need your eyes @stuartleeks 

https://github.com/lawrencegripper/azbrowse/pull/204/files
