### ISSUE TITLE
Devcontainer missing analysis tools

### ISSUE THREAD

**Issue by bengreenier** [lawrencegripper/azbrowse#210]
The Go extension complains about missing analysis tools when opening the container.

> Note: If you choose to update, it seems to persist it into the container (until it is rebuilt), so it's not everytime the project is opened.

![image](https://user-images.githubusercontent.com/1167891/71815830-a0310f80-3078-11ea-889d-31c88dcab3d8.png)

Seems there's 1 of 2 actions to take here:
+ Document that you should close/ignore the popup error
+ Update the Dockerfile to install these tools:

```
Installing 5 tools at /go/bin in module mode.
  gocode
  gopkgs
  gocode-gomod
  godef
  goreturns
```

**Comment by lawrencegripper** [comment]
So I've removed those tools deliverable as on (possibly faulty) testing I found that the language server now does all the stuff needed so they weren't being used and just bloated out the container.

**Comment by bengreenier** [comment]
Ok cool - I don't see a flag in Go extension settings to disable this warning, so I think we should document it. Do you have a place in mind that this kind of doc should go? A new FAQ page off of [docs](https://github.com/lawrencegripper/azbrowse/blob/master/docs/README.md) maybe?

**Comment by lawrencegripper** [comment]
Yeah FAQ sounds good or maybe updating the contributing doc. I have some changes here for the contrib doc which move it to encourage use of devcontainer.

**Comment by bengreenier** [comment]
With #212 this no longer pops for the user (though it is still present in the toolbar at the bottom) - but much lower prio, IMHO.

**Comment by lawrencegripper** [comment]
Nice find on the property to silence this one. :)

**Comment by lawrencegripper** [comment]
Closing as this one is all done (well pretty much)
