### ISSUE TITLE
UI minor usability improvement

### ISSUE THREAD

**Issue by daltskin** [lawrencegripper/azbrowse#214]
When you select a resource group for deletion, the notification window will show the below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1678318/72170324-9e44b480-33c8-11ea-919d-41885b08f4bf.png)

Pressing ESC does nothing, it only accepts CTRL+Y or CTRL+N.  Would be good if the ESC keypress was trapped as a CTRL+N.

**Comment by stuartleeks** [comment]
My initial response to this was "oooh, that'd be nice!"

It might be tricky to implement reliably as the delete functionality allows you to navigate around the tree selecting things to delete and there are places where you could use `Esc` in that naviation. E.g. clearing the filter dialog or command palette.

**Comment by lawrencegripper** [comment]
We could find another shortcut like `CTRL+X` or something similar in place of `ESC`

**Comment by daltskin** [comment]
Do people often delete more than 1 item at a time?  ie. do you need the ability to navigate around to select more than 1 item?  TBH: I didn't realize this was possible using the app, I was just trying to delete a resource group and thought I'd actually broken something because of this, and the Esc key did nothing to clear the notifications!

**Comment by stuartleeks** [comment]
I use multiple deletes quite a lot :-)
E.g. for periodic cleanup of my subscription where I'll delete several resource groups in one go, or for cleaning up images in ACR

**Comment by lawrencegripper** [comment]
+1 on this I use multi-delete a lot

**Comment by daltskin** [comment]
ok, so there are 2 UI usability points here then :)

1. Can ESC be replaced with another key combo
2. Multi-delete feature isn't obvious for first timers

Granted this might be covered in the documentation, but I didn't read it ;)

**Comment by stuartleeks** [comment]
Good feedback, thanks!

**Comment by lawrencegripper** [comment]
![image](https://user-images.githubusercontent.com/1939288/102902889-74649080-4467-11eb-85dc-10cab515d8b4.png)

Finally got round to fixing this one up!
