### ISSUE TITLE
Add snap support for installing on ubuntu

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#230]
As per https://snapcraft.io/docs/getting-started, adding snap support would allow `snap install azbrowse` on Ubuntu.

**Comment by lawrencegripper** [comment]
Yup, want

**Comment by lawrencegripper** [comment]
Looking at it I think `goreleaser` supports snap so hopefully able to wire this up to the existing release stuff.

**Comment by stuartleeks** [comment]
oooh, nice!

I'm assuming it makes sense for you to do this so that you can create the account on snapcraft.io?

**Comment by lawrencegripper** [comment]
Yeah sure I'll pick this one up. Have a feeling I've tried once before and hit some fun with docker and snapd - lets see how it goes.

**Comment by lawrencegripper** [comment]
Discussion around confinement raised here: https://forum.snapcraft.io/t/request-classic-confinement-for-snap-azbrowse/18240

**Comment by lawrencegripper** [comment]
Closing as live in the snap store.
