### ISSUE TITLE
Bug: `az graph command failed`

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#258]
If the `resource-graph` extension for `az` CLI is not installed then the following error is seen in the status panel:

```
 [Debug] [Error] az graph command failed            
```

A workaround is to install the `resource-graph` extension:

```
sudo az extension add -n resource-graph
```

---

```
$ azbrowse version
2.0.147311918
952ae91
2020-06-25T10:50:06Z
go version go1.14.4 linux/amd64
linux/amd64
```

**Comment by lawrencegripper** [comment]
Ah interesting, I thought this was a default install the CLI - woops!

I’ll move it to use the REST API and that should fix things up.
