### ISSUE TITLE
Feature: filter subscriptions

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#26]
My working pattern means that I'm normally working with a subset of the subscriptions available to me and it would be great to be able to filter the subscriptions show in this case (easier to navigate, filtered search results etc).

**Comment by lawrencegripper** [comment]
Sounds like a great addition. The `store.go` file can be extended to add support for persisting the filters into the boltdb too 

https://github.com/lawrencegripper/azbrowse/blob/master/storage/store.go#L96

**Comment by stuartleeks** [comment]
My desire to have this has been lessened by the navigate command. Is it still worth tracking this?

**Comment by lawrencegripper** [comment]
Lets close out for now, we can always reopen later as needed.
