### ISSUE TITLE
Gofish formula

### ISSUE THREAD

**Issue by ams0** [lawrencegripper/azbrowse#270]
Added https://github.com/fishworks/fish-food/pull/906 to easily install on multiple platforms.

**Comment by lawrencegripper** [comment]
Nice! Thanks :+1: 

Is there a way to have the formula take the latest release? No worries if not as the auto-update will handle upgrading people to latest.

**Comment by bacongobbler** [comment]
> Is there a way to have the formula take the latest release?

This may be possible assuming that you could write a Lua script that fetches both the latest release version and the corresponding shasums for the release assets, similar to how you could do this for homebrew formulas.
