### ISSUE TITLE
Investigate if upgrading cobra version allows autocomplete on alias

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#279]
I'd like `azb -<TAB>` to autocomplete if `alias azb=azbrowse` is set.

**Comment by stuartleeks** [comment]
How neatly packaged do you want this to be?

E.g, would this be sufficient?

```bash
complete -F __start_azbrowse azb
```
From https://github.com/stuartleeks/dotfiles/blob/main/aliases/load.sh#L24

**Comment by lawrencegripper** [comment]
Oh cool that's what I want!
