### ISSUE TITLE
Chocolatey package 

### ISSUE THREAD

**Issue by kilasuit** [lawrencegripper/azbrowse#283]
I saw you have this on scoop, do you have an plans on releasing to chocolatey as well?

**Comment by lawrencegripper** [comment]
Hi,

Currently don’t have any plans to support Choco package but I’d welcome a contribution. Starting point would likely a proposal on how to fit this into the current deployment process.

We use Go Releaser to build all the existing packages and this doesn’t support choco at the moment https://goreleaser.com/. One route would be to add support into Go Releaser for packaging to choco.
