### ISSUE TITLE
Scrolling pgDown not working correctly on RHS panel

### ISSUE THREAD

**Issue by daltskin** [lawrencegripper/azbrowse#292]
When viewing Activity Log output within a Resource Group, the content on the right hand side does not scroll correctly.

pgDown key not working.  If you use the down arrow key to scroll past the first few lines.  Press pgDown again and it will return you to the beginning of the document?!

![image](https://user-images.githubusercontent.com/1678318/105057191-e0d5ae00-5a6c-11eb-97a5-7e5f1698d47e.png)

Now use the down arrow key to scroll further into the document and use the pgUp key, which will work as expected.

Tested with multiple resource groups, each exhibiting the same pgDown key problem when viewing the Activity Log content

**Comment by lawrencegripper** [comment]
Yeah think this is my bad maths but think @stuartleeks has come to the rescue on this one with a PR already!
