### ISSUE TITLE
Sorry a crash occurred Error: Failed to set cursor position

### ISSUE THREAD

**Issue by daltskin** [lawrencegripper/azbrowse#293]
Whilst applying a filter within Activity Log, the cli crashed.  

![image](https://user-images.githubusercontent.com/1678318/105058300-f9929380-5a6d-11eb-95e6-c50700b8ba81.png)

Steps to repo:

- Select Activity Log
- Press / (to apply filter)
- Enter any filter and press ENTER

Upon ENTER being pressed the cli crashes.

Stack Trace:                                                                                                                                                                                                     goroutine 1 [running]:                                                                                                                                                                                           runtime/debug.Stack(0xf04850, 0x13, 0x12b90060)                                                                                                                                                                          /usr/local/go/src/runtime/debug/stack.go:24 +0x83                                                                                                                                                        github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithClrceGroups/RG-PowerBI/<activitylog>'

**Comment by daltskin** [comment]
After resizing and clearing the terminal, this is now working ¯\_(ツ)_/¯

**Comment by lawrencegripper** [comment]
Ooh funky, let me know if it happens again. Did the stack trace have anything else or just finish here?

**Comment by daltskin** [comment]
That's all I could (barely) see on the screen!
