### ISSUE TITLE
cross-subscription search

### ISSUE THREAD

**Issue by serbrech** [lawrencegripper/azbrowse#306]
I often know the name of a resource, but I couldn't tell which subscription it's in, (one of the many test subs picked by our CI at random)

in the portal, I can paste the resource name, and it will search in all subscription (or pre-selected subscriptions)

I don't think there is a way to do this in azbrowse, and it would be a nice addition.

**Comment by lawrencegripper** [comment]
I wonder if with some tweaks to '--navigate' option could get something close to this UX.

I believe I used the resource graph stuff to pull pack all resources so in theory could search by just name and autocomplete.

**Comment by lawrencegripper** [comment]
@serbrech What do you think? Are you looking for this as a command link for launching or while in the app?

Happy to take a PR for this is it's something you'd like to work on. We have the idea of `handlers` which can be bound to keys and appear in the command pannel. 

https://github.com/lawrencegripper/azbrowse/blob/2f745e1225ec43e0f08ccbdaec9e445cc0ae8c35/internal/pkg/keybindings/types.go#L7-L13

Here is an example: https://github.com/lawrencegripper/azbrowse/blob/2f745e1225ec43e0f08ccbdaec9e445cc0ae8c35/internal/pkg/keybindings/itemhandlers.go#L108
