### ISSUE TITLE
Add ability to pin or favourite resources

### ISSUE THREAD

**Issue by daltskin** [lawrencegripper/azbrowse#325]
Just an idea, but it would be nice to be able to mark a resource as a favourite or be able to pin it.  Especially when navigating things like cosmos, where you have to go through a number of steps to get to see the data within a resource eg:

To view the contents of a Cosmos SQL container requires 7 navigation steps:

Resource Group > [Microsoft.DocumentDB/DatabaseAccount] > sqlDatabases > {name of db} > containers > {name of container} > Documents

If you could pin at the Documents level for next time you open up azbrowse would be a nice addition :)

**Comment by lawrencegripper** [comment]
Sounds like a good idea, you up for working on a PR for it? Happy to pair a bit.

As a workaround for now have you tried out the 
```
--navigate 
```
Command line option? You can use CTRL+P -> copy ID to get the ID to use with it.

Should allow you to jump to the resource. There is also a 'resume' option to jump back to last used location

**Comment by lawrencegripper** [comment]
Doc on command line options: https://github.com/lawrencegripper/azbrowse/blob/main/docs/commandline/azbrowse.md

**Comment by lawrencegripper** [comment]
@daltskin I have good news! You can now create custom views of your fav resources with `Azure Resource Graph` queries. 

Details/docs here: https://github.com/lawrencegripper/azbrowse/blob/main/docs/azure-resource-graph.md

Going to close this one off as think this fits the bill but shout if it doesn't do the trick or you have any feedback.

**Comment by daltskin** [comment]
Great work @lawrencegripper - looking forward to using this :)

**Comment by lawrencegripper** [comment]
Cool, let me know how you get on with it - docs and all. It's a new feature so may have some bumps to iron out.
