### ISSUE TITLE
Enhancement: Handle long breadcrumbs

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#34]
As mentioned in #33, when your subscription name is too long the breadcrumbs get truncated and it becomes a bit of a mess. Do you think it'd be better to use a static breadcrumbe i.e. `Subs > Resource groups` or try to truncate and elipise the subscription name to 8 or so characters until it renders a little more cleanly?
![azbrowse_list3](https://user-images.githubusercontent.com/7241190/52277111-c7083280-294b-11e9-99d9-b8c07ed764af.PNG)

**Comment by lawrencegripper** [comment]
Fixed in latest release
