### ISSUE TITLE
azbrowse crash on startup, then fine second time around

### ISSUE THREAD

**Issue by martinpeck** [lawrencegripper/azbrowse#401]
Started `azbrowse` after a long period of not using it...

```
$ azbrowse
2022/01/18 08:53:05 Checking for updates
2022/01/18 08:53:08 Successfully updated to version 2.1.554


Sorry a crash occurred
 Error: Request failed: Failed to acquire auth token: signal: killed (try running 'az account get-access-token' to get more details)

Please visit https://github.com/lawrencegripper/azbrowse/issues to raise a bug.
When raising please provide the details below in the issue.
Note `Navigation Tree` may contain sensitive information, please review before posting.

Stack Trace:
goroutine 103 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithCleanup()
	/home/runner/work/azbrowse/azbrowse/internal/pkg/errorhandling/recovery.go:82 +0x157
panic({0x1dbf720, 0xc0003e0170})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/lawrencegripper/azbrowse/pkg/armclient.(*Client).PopulateResourceAPILookup(0xc00099e000, {0x2ada4e0, 0xc0000aa000}, 0xc00099e000)
	/home/runner/work/azbrowse/azbrowse/pkg/armclient/armclient.go:318 +0x71f
main.startPopulatingList.func1()
	/home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:190 +0xc5
created by main.startPopulatingList
	/home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:182 +0xd6

Navigation Tree:
```

I then ran `az account show` to double check I was signed in (I was).

I ran `azbrowse` second time and it worked fine (presumably, at this point, the newer version as it told me it had skipped the check for updates).

**Comment by lawrencegripper** [comment]
Hmmmm thats an odd one.

Any idea if this repo's for other folks when they update?

**Comment by lawrencegripper** [comment]
Should be another update for ARM specs shipping shortly. @martinpeck can you let me know if you see another crash when updating to that version? 

#402

**Comment by martinpeck** [comment]
@lawrencegripper yep...same issue....

``` bash
~/dev
$ azbrowse
2022/02/28 13:35:54 Checking for updates
2022/02/28 13:35:57 Successfully updated to version 2.1.563


Sorry a crash occurred
 Error: Request failed: Failed to acquire auth token: signal: killed (try running 'az account get-access-token' to get more details)


Please visit https://github.com/lawrencegripper/azbrowse/issues to raise a bug.
When raising please provide the details below in the issue.
Note `Navigation Tree` may contain sensitive information, please review before posting.

Stack Trace:
goroutine 43 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithCleanup()
	/home/runner/work/azbrowse/azbrowse/internal/pkg/errorhandling/recovery.go:82 +0x157
panic({0x1dc3300, 0xc000361080})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/lawrencegripper/azbrowse/pkg/armclient.(*Client).PopulateResourceAPILookup(0xc000c40140, {0x2b29d80, 0xc0000a8000}, 0xc000c40140)
	/home/runner/work/azbrowse/azbrowse/pkg/armclient/armclient.go:318 +0x71f
main.startPopulatingList.func1()
	/home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:190 +0xc5
created by main.startPopulatingList
	/home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:182 +0xd6

Navigation Tree:
```

**Comment by martinpeck** [comment]
and, as before, 2nd attempt (after the upgrade, I assume) works fine

**Comment by lawrencegripper** [comment]
um no thanks bot.

**Comment by lawrencegripper** [comment]
Full disclosure, I don't have the head space at the moment to dig into this one. I think it will continue to occur on each update. Marking it as up for grabs if anyone has time to do some digging.

**Comment by tmeckel** [comment]
Perhaps my PR #431 will solve the issue here.

**Comment by lawrencegripper** [comment]
That's now shipped. @martinpeck do you still see a crash after update?

**Comment by martinpeck** [comment]
Will I see the fix first time of updating, or next time?
I’ve not used `azbrowse` for a while (months) so I just ran it, and that caused it to update itself.
I saw the error as per the original post, but (as before) the update succeeds.

**Comment by lawrencegripper** [comment]
Thanks for giving it a try, sounds like this is still a problem.

**Comment by tmeckel** [comment]
@martinpeck I'm a bit confused, did you use the new version of `azbrowse` and got the same error as before. Or, because lack of time, didn't you run a new "test" and only clarified what happened last time?

**Comment by martinpeck** [comment]
OK...so, here's what I did (and also what I've just done):

1. open terminal
2. run `azbrowse`
3. observe that an update occurs

EXPECTED:

- azbrowse launches without error

ACTUAL:

```
$ azbrowse
2023/03/02 16:51:07 Checking for updates
2023/03/02 16:51:10 Successfully updated to version 2.1.679


Sorry a crash occurred
 Error: Request failed: Failed to acquire auth token: failed to get token: failed to get subscription list: DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
	EnvironmentCredential: missing environment variable AZURE_TENANT_ID
	ManagedIdentityCredential: IMDS token request timed out
	AzureCLICredential: signal: killed


Please visit https://github.com/lawrencegripper/azbrowse/issues to raise a bug.
When raising please provide the details below in the issue.
Note `Navigation Tree` may contain sensitive information, please review before posting.

Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithCleanup()
	/home/runner/work/azbrowse/azbrowse/internal/pkg/errorhandling/recovery.go:83 +0x157
panic({0x1ac0360, 0xc000476320})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/lawrencegripper/azbrowse/pkg/armclient.(*Client).PopulateResourceAPILookup(0xc0003e46e0?, {0x26a17c8?, 0xc00011c000?}, 0xc0003e46e0)
	/home/runner/work/azbrowse/azbrowse/pkg/armclient/armclient.go:318 +0x725
main.startPopulatingList.func1()
	/home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:190 +0xca
created by main.startPopulatingList
	/home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:182 +0xd1

Navigation Tree:
```

**Comment by martinpeck** [comment]
As you can see, the crash happened (for me) again. That said, it's slightly different in terms of the error message.

Running `azbrowse` a second time works fine.

**Comment by martinpeck** [comment]
@tmeckel : I re-ran my "test" (i.e. ran `azbrowse` in my terminal) and saw the crash, and that's what I've just done again today (and, again, see the crash).

**Comment by tmeckel** [comment]
@martinpeck  Thank's for the exmplantion! Appreciated 😀And I'm "happy" to see the old exception message vanished and a message from the Microsoft Azure Authentication Framework showing up. Unfortunately with the same problem as before, but now at least with the new framework. 

I wonder though why `az cli` is hard terminated (`AzureCLICredential: signal: killed`) on your machine. That's odd. Seems to me it's more an issue with Azure CLI itself than with `azbrowse`.

**Comment by martinpeck** [comment]
> Seems to me it's more an issue with Azure CLI itself than with azbrowse.

Could be, but I spend most of my day using `az` without issue.

**Comment by martinpeck** [comment]
I'm on MacOS (Ventura now, but the original bug would have been on a previous release)
I'm using iTerm2, zsh, and have latest az.

**Comment by martinpeck** [comment]
Is there a way I could "trick" `azbrowse` into thinking it always needed to do an update?
i.e. can I force azbrowse into the upgrade path so I can repeatedly see the error?
If so, it might help me diagnose the issue.
