### ISSUE TITLE
Get all service principals and applications (paging)

### ISSUE THREAD

**Issue by tiwood** [lawrencegripper/azbrowse#428]
The application and service principal endpoints may only return a limited result set, indicated by the presence of `@odata.nextLink`.
azbrowse should automatically follow these nextLinks until all results are available.

Thanks for building this great tool!

## References
https://learn.microsoft.com/en-us/graph/paging

**Comment by lawrencegripper** [comment]
Thanks, glad you like it. 

We probably can't iterate all items in one shot as we'd fail with large list sizes, for example an AD tenant with 1000's of service principals in it. 

@stuartleeks worked on paging in the `StorageBlob` provider, it handles this by adding a `next` item to the bottom of the list which will load the following page. 

https://github.com/lawrencegripper/azbrowse/blob/09058b563769277b51856eade59056330f04794d/internal/pkg/expanders/storageBlob.go#L485

Would be interesting to see if we can make this generic over a larger number of providers.

One option, which is currently available and may suit your use case, is to define a custom Resource Graph query which returns the items which are specifically useful to you: https://github.com/lawrencegripper/azbrowse/blob/main/docs/azure-resource-graph.md as a workaround.

**Comment by tiwood** [comment]
If I understood correctly, the issue is not the paging itself and the time it may take to get all elements, the problem is we don't want the number of items in the list to be greater `n` right?

Is this for technical or usability reasons?

I just queried all identities in our tenant (nearly 3000) and it took around 9 seconds to get the properties that are required to build the item list. It would work for me if I could use this list to filter and access the application I care about.

Regarding the custom query, AFAIK Resource Graph does not contain Azure AD objects.

**Comment by lawrencegripper** [comment]
> I just queried all identities in our tenant (nearly 3000) and it took around 9 seconds

Yeah I work in a tenant where we have 1000's, potentially offering configuration page size/walking would work here. By default we enumerate x and offer a `next page` button but you can set that to `y`.

I don't have time to pick up this feature request at the moment but it's something I see value in being added. I'll mark it as up for grabs and happy to help folks who are willing to take it on.
