### ISSUE TITLE
Startup crash: Failed to get subscription list

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/azbrowse#478]
I just installed `azbrowse` in a dev container (Debian 11) and get the following error on startup:

```
Sorry a crash occurred
 Error: Request failed: Failed to acquire auth token: failed to get token: failed to get subscription list: DefaultAzureCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
--------------------------------------------------------------------------------
connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
--------------------------------------------------------------------------------



Please visit https://github.com/lawrencegripper/azbrowse/issues to raise a bug.
When raising please provide the details below in the issue.
Note `Navigation Tree` may contain sensitive information, please review before posting.

Stack Trace:
goroutine 25 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithCleanup()
        /home/runner/work/azbrowse/azbrowse/internal/pkg/errorhandling/recovery.go:83 +0x157
panic({0xebd020, 0xc0000912c0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/lawrencegripper/azbrowse/pkg/armclient.(*Client).PopulateResourceAPILookup(0xc0003b8690?, {0x1a9cb28?, 0xc0000380a0?}, 0xc0003b8690)
        /home/runner/work/azbrowse/azbrowse/pkg/armclient/armclient.go:318 +0x725
main.startPopulatingList.func1()
        /home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:190 +0xca
created by main.startPopulatingList
        /home/runner/work/azbrowse/azbrowse/cmd/azbrowse/main.go:182 +0xd1

Navigation Tree:
```

I tried running with the `--subscription` switch to specify the subscription, but still get the same error

**Comment by stuartleeks** [comment]
This seems to be an issue with the `ChainedTokenCredential` that is returned from `NewDefaultAzureCredential`. The handling of the managed identity credential attempt (which is in the chain before the Azure CLI handler) returns a `credentialUnavailableError` and then chained handler stops processing at that point :-(

If we don't want the default behaviour (checking for managed identity etc) then the auth could switch over to `NewAzureCLICredential` instead of `NewDefaultAzureCredential`

**Comment by lawrencegripper** [comment]
Thanks for digging into this one, this is far from ideal.

Playing back what I've understood, the new sign in library is detecting that the codespace is an Azure VM and then attempting to get a token. When it gets a 403 back from the token endpoint it bombs out rather than falling back to the `NewAzureCLICredential` handler

**Comment by stuartleeks** [comment]
No, this isn't in codespaces - this is all in a dev container on my local machine! 

I've created a temporary, local build that directly uses `NewAzureCLICredential`. Is that something that is worth a PR, or are there other sign-in approaches that you want to keep?

**Comment by lawrencegripper** [comment]
Ah ok, that makes sense. I just tried to reproduce it in a local devcontainer and got:

```
vscode@gripdev-ryzen9:/workspaces/azbrowse$ ./azbrowse
2023/04/25 18:42:59 Checking for updates
2023/04/25 18:43:04 Current version is the latest


Sorry a crash occurred
 Error: Request failed: Failed to acquire auth token: failed to get token: failed to get subscription list: DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
        ManagedIdentityCredential: IMDS token request timed out
        AzureCLICredential: Azure CLI not found on path 
```

Which makes more sense.

The error you see `GET http://169.254.169.254/metadata/identity/oauth2/token` returning a `403` suggests that something in your setup is answering that request. I wouldn't have expected this as that's [the azure metadata endpoint.](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service)

What does `curl http://169.254.169.254/metadata/identity/oauth2/token` give you from within the devcontainer?

```
azbrowse$ curl http://169.254.169.254/metadata/identity/oauth2/token
curl: (7) Failed to connect to 169.254.169.254 port 80: No route to host
```

**Comment by stuartleeks** [comment]
I get this:

```
$ curl http://169.254.169.254/metadata/identity/oauth2/token
connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
```

**Comment by lawrencegripper** [comment]
Fun! 

Yeah if you can spin up a PR with the move away from Chained provider would be good to ship.

I'm not aware of anyone using MSI to auth and we can always revisit if that comes up.
