### ISSUE TITLE
Trying to delete a subscription crashes the program

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#53]
If you try to delete a subscription (double confirm) it will crash the program, this should probably just be a no-op.

**Comment by lawrencegripper** [comment]
Agreed, I've added in the concept of `ExpantNotSupported` type for `ExpandURL`. We should probably do something similar for `DeleteNotSupported` in the `DeleteURL`.

**Comment by lawrencegripper** [comment]
More generally I'd used `panic` quite liberally in the current code, this probably needs to move to a more sympathetic approach maybe simply listed them in the `statusbar` as failed.

**Comment by stuartleeks** [comment]
I just added support for `DELETE` in my swagger PR which required me to add a test on whether `DELETE` is supported for a tree node. Doing this fixes this issue :-)

**Comment by lawrencegripper** [comment]
Nice!
