### ISSUE TITLE
Resource status font does not display correctly on MacOS

### ISSUE THREAD

**Issue by martinpeck** [lawrencegripper/azbrowse#55]
I've tried various fonts, and I've tried iTerm2 vs Terminal, but I still get a question mark instead of the expected unicode glyph when I build and run `azbrowse`. I've not investigated this, and fully intend do, but wanted to log this before I forget.

![image](https://user-images.githubusercontent.com/1524451/53185014-0f834980-35f6-11e9-9e85-50eb5ce0e55c.png)

**Comment by martinpeck** [comment]
Looks like it may only be the Succeeded Status Icon that has an issue, as I see all of the others in the Help screen.

![image](https://user-images.githubusercontent.com/1524451/53189724-0dbe8380-3600-11e9-88f8-d4a07042dc61.png)

**Comment by martinpeck** [comment]
@lawrencegripper is the missing character "white sun"...?

https://unicode-table.com/en/1F323/

On Windows this font renders fine, but on OSX, and on iOS, it doesn't appear to work.

**Comment by lawrencegripper** [comment]
Nice find - thanks!

That is the one indeed. I'm not set on it and have toyed with other things, like a tick, in the past. Happy to accept a PR that uses another similar or better char.

**Comment by martinpeck** [comment]
This version looks to work on MacOS https://unicode-table.com/en/263C/
I'm going to confirm it also works on iOS (once i've saved this comment) and will submit a PR shortly
