### ISSUE TITLE
azbrowse crashes on startup, and navigation, with no network

### ISSUE THREAD

**Issue by martinpeck** [lawrencegripper/azbrowse#56]
Clearly, without the internets `azbrowse` is powerless, but the app currently crashes/panics in these situations. Probably not a high priority issue, given the user base, but might be nice to clean up.

**Comment by lawrencegripper** [comment]
Agreed, nice one to have on the backlog. I'd suggest that we exist more gracefully in these scenarios with a nice error saying "You don't have any internets" or something similar. Sound like a good plan?
