### ISSUE TITLE
Respect alternatives system for default editor

### ISSUE THREAD

**Issue by ohthehugemanatee** [lawrencegripper/azbrowse#91]
Most Linux distros implement the [alternatives system](https://linux.die.net/man/8/update-alternatives) to let users configure default programs across the alternatives that are installed on their system. (choose your editor with `update-alternatives --config editor`).

We should respect this configuration.

**Comment by lawrencegripper** [comment]
Love this idea, we've got to be a bit conscious that the tools runs over Mac, Linux and Windows so whatever we do should be cross plat. 

Would love to see a PR to tackle this one or proposal around how to tackle. 

One option which springs to mind is maybe using platform specific rules where appropriate and allowing an override in a settings file or envar. 

We currently use `[https://github.com/skratchdot/open-golang/](https://github.com/skratchdot/open-golang/)` to select the correct browser. It may already have the logic to select the correct editor for a `.json` file. 

One complexity is monitoring the editor we've loaded to see when it's `done` with the file. I think the current method is `vscode` specific and monitors the `tab` opened. One option is to monitor the process but for multi-tabbed editors this means closing the whole editor to continue, not ideal. Another would be to monitor the file and observe save operations but this might not be the UX people expect `Updated Azure on Save` feels like it might catch people out. 

What do you think?

cc @stuartleeks

**Comment by stuartleeks** [comment]
I am looking at something related to this to enable Vs code to work as an editor on WSL so will take a look 😀

**Comment by lawrencegripper** [comment]
This this is good to close now as it's shipped in #97
